parameters:
#    totales.example.class: LanguageFirst\TotalesBundle\Example

services:
#    totales.example:
#        class: %totales.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
