SeccionesFaseBundle:
    resource: "@SeccionesFaseBundle/Resources/config/routing.yml"
    prefix:   /

FaseTestBundle:
    resource: "@FaseTestBundle/Resources/config/routing.yml"
    prefix:   /

TotalesTestRespondidosBundle:
    resource: "@TotalesTestRespondidosBundle/Resources/config/routing.yml"
    prefix:   /

TestRespondidosBundle:
    resource: "@TestRespondidosBundle/Resources/config/routing.yml"
    prefix:   /

TotalesBundle:
    resource: "@TotalesBundle/Resources/config/routing.yml"
    prefix:   /

TestBundle:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
