parameters:
#    respuestas_preguntas.example.class: LanguageFirst\RespuestasPreguntasBundle\Example

services:
#    respuestas_preguntas.example:
#        class: %respuestas_preguntas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
