parameters:
#    preguntas_seccion.example.class: LanguageFirst\PreguntasSeccionBundle\Example

services:
#    preguntas_seccion.example:
#        class: %preguntas_seccion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
